package tragicneko.tragicmc.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMegaCryse extends ModelBase
{
	//fields
	ModelRenderer Middle;
	ModelRenderer Top;
	ModelRenderer Bottom;
	ModelRenderer Left;
	ModelRenderer Right;
	ModelRenderer TopSemi;
	ModelRenderer BottomSemi;
	ModelRenderer LeftSemi;
	ModelRenderer RightSemi;
	ModelRenderer TLBar;
	ModelRenderer TRBar;
	ModelRenderer BRBar;
	ModelRenderer BLBar;
	ModelRenderer EyeRight;
	ModelRenderer EyeLeft;
	ModelRenderer Middle2;
	ModelRenderer LeftSemi2;
	ModelRenderer TopSemi2;
	ModelRenderer RightSemi2;
	ModelRenderer BottomSemi2;
	ModelRenderer TLBar2;
	ModelRenderer BLBar2;
	ModelRenderer BRBar2;
	ModelRenderer TRBar2;
	ModelRenderer Top2;
	ModelRenderer Right2;
	ModelRenderer Left2;
	ModelRenderer Bottom2;
	ModelRenderer EyeRight2;
	ModelRenderer EyeLeft2;
	ModelRenderer Bottom3;
	ModelRenderer Middle3;
	ModelRenderer Top3;
	ModelRenderer Right3;
	ModelRenderer Left3;
	ModelRenderer BottomSemi3;
	ModelRenderer TopSemi3;
	ModelRenderer LeftSemi3;
	ModelRenderer RightSemi3;
	ModelRenderer TRBar3;
	ModelRenderer TLBar3;
	ModelRenderer BRBar3;
	ModelRenderer BLBar3;
	ModelRenderer EyeRight3;
	ModelRenderer EyeLeft3;

	public ModelMegaCryse()
	{
		textureWidth = 64;
		textureHeight = 32;

		Middle = new ModelRenderer(this, 0, 0);
		Middle.addBox(-1F, -1F, -1.5F, 2, 2, 3);
		Middle.setRotationPoint(-2F, 9F, 0F);
		Middle.setTextureSize(64, 32);
		Middle.mirror = true;
		setRotation(Middle, 0F, 0F, 0F);
		Top = new ModelRenderer(this, 0, 0);
		Top.addBox(-1F, -1F, -1F, 2, 2, 2);
		Top.setRotationPoint(-2F, 3F, 0F);
		Top.setTextureSize(64, 32);
		Top.mirror = true;
		setRotation(Top, 0F, 0F, 0F);
		Bottom = new ModelRenderer(this, 0, 0);
		Bottom.addBox(-1F, -1F, -1F, 2, 2, 2);
		Bottom.setRotationPoint(-2F, 15F, 0F);
		Bottom.setTextureSize(64, 32);
		Bottom.mirror = true;
		setRotation(Bottom, 0F, 0F, 0F);
		Left = new ModelRenderer(this, 0, 0);
		Left.addBox(-1F, -1F, -1F, 2, 2, 2);
		Left.setRotationPoint(3F, 9F, 0F);
		Left.setTextureSize(64, 32);
		Left.mirror = true;
		setRotation(Left, 0F, 0F, 0F);
		Right = new ModelRenderer(this, 0, 0);
		Right.addBox(-1F, -1F, -1F, 2, 2, 2);
		Right.setRotationPoint(-7F, 9F, 0F);
		Right.setTextureSize(64, 32);
		Right.mirror = true;
		setRotation(Right, 0F, 0F, 0F);
		TopSemi = new ModelRenderer(this, 0, 0);
		TopSemi.addBox(-1F, -5F, -1F, 1, 4, 1);
		TopSemi.setRotationPoint(-2F, 9F, 0F);
		TopSemi.setTextureSize(64, 32);
		TopSemi.mirror = true;
		setRotation(TopSemi, 0F, 0F, 0F);
		BottomSemi = new ModelRenderer(this, 0, 0);
		BottomSemi.addBox(0F, 1F, 0F, 1, 4, 1);
		BottomSemi.setRotationPoint(-2F, 9F, 0F);
		BottomSemi.setTextureSize(64, 32);
		BottomSemi.mirror = true;
		setRotation(BottomSemi, 0F, 0F, 0F);
		LeftSemi = new ModelRenderer(this, 0, 0);
		LeftSemi.addBox(1F, -1F, 0F, 3, 1, 1);
		LeftSemi.setRotationPoint(-2F, 9F, 0F);
		LeftSemi.setTextureSize(64, 32);
		LeftSemi.mirror = true;
		setRotation(LeftSemi, 0F, 0F, 0F);
		RightSemi = new ModelRenderer(this, 0, 0);
		RightSemi.addBox(-4F, 0F, -1F, 3, 1, 1);
		RightSemi.setRotationPoint(-2F, 9F, 0F);
		RightSemi.setTextureSize(64, 32);
		RightSemi.mirror = true;
		setRotation(RightSemi, 0F, 0F, 0F);
		TLBar = new ModelRenderer(this, 0, 0);
		TLBar.addBox(-3F, -5F, -1F, 6, 1, 1);
		TLBar.setRotationPoint(-2F, 9F, 0F);
		TLBar.setTextureSize(64, 32);
		TLBar.mirror = true;
		setRotation(TLBar, 0F, 0F, 0.7435722F);
		TRBar = new ModelRenderer(this, 0, 0);
		TRBar.addBox(-3F, 4F, 0F, 6, 1, 1);
		TRBar.setRotationPoint(-2F, 9F, 0F);
		TRBar.setTextureSize(64, 32);
		TRBar.mirror = true;
		setRotation(TRBar, 0F, 0F, 2.379431F);
		BRBar = new ModelRenderer(this, 0, 0);
		BRBar.addBox(-3F, 4F, -1F, 6, 1, 1);
		BRBar.setRotationPoint(-2F, 9F, 0F);
		BRBar.setTextureSize(64, 32);
		BRBar.mirror = true;
		setRotation(BRBar, 0F, 0F, 0.7435722F);
		BLBar = new ModelRenderer(this, 0, 0);
		BLBar.addBox(-3F, -5F, 0F, 6, 1, 1);
		BLBar.setRotationPoint(-2F, 9F, 0F);
		BLBar.setTextureSize(64, 32);
		BLBar.mirror = true;
		setRotation(BLBar, 0F, 0F, 2.379431F);
		EyeRight = new ModelRenderer(this, 0, 10);
		EyeRight.addBox(-3F, -2F, -2F, 1, 1, 1);
		EyeRight.setRotationPoint(-2F, 9F, 0F);
		EyeRight.setTextureSize(64, 32);
		EyeRight.mirror = true;
		setRotation(EyeRight, 0F, 0F, 0F);
		EyeLeft = new ModelRenderer(this, 0, 10);
		EyeLeft.addBox(2F, -3F, -2F, 1, 1, 1);
		EyeLeft.setRotationPoint(-2F, 9F, 0F);
		EyeLeft.setTextureSize(64, 32);
		EyeLeft.mirror = true;
		setRotation(EyeLeft, 0F, 0F, 0F);
		Middle2 = new ModelRenderer(this, 0, 0);
		Middle2.addBox(0F, 0F, 0F, 2, 2, 3);
		Middle2.setRotationPoint(9F, 0F, 0.5F);
		Middle2.setTextureSize(64, 32);
		Middle2.mirror = true;
		setRotation(Middle2, 0F, 0F, 0F);
		LeftSemi2 = new ModelRenderer(this, 0, 0);
		LeftSemi2.addBox(0F, 0F, 0F, 3, 1, 1);
		LeftSemi2.setRotationPoint(11F, 0F, 2F);
		LeftSemi2.setTextureSize(64, 32);
		LeftSemi2.mirror = true;
		setRotation(LeftSemi2, 0F, 0F, 0F);
		TopSemi2 = new ModelRenderer(this, 0, 0);
		TopSemi2.addBox(0F, -4F, 0F, 1, 4, 1);
		TopSemi2.setRotationPoint(9F, 0F, 1F);
		TopSemi2.setTextureSize(64, 32);
		TopSemi2.mirror = true;
		setRotation(TopSemi2, 0F, 0F, 0F);
		RightSemi2 = new ModelRenderer(this, 0, 0);
		RightSemi2.addBox(-3F, 0F, 0F, 3, 1, 1);
		RightSemi2.setRotationPoint(9F, 1F, 1F);
		RightSemi2.setTextureSize(64, 32);
		RightSemi2.mirror = true;
		setRotation(RightSemi2, 0F, 0F, 0F);
		BottomSemi2 = new ModelRenderer(this, 0, 0);
		BottomSemi2.addBox(0F, 0F, 0F, 1, 4, 1);
		BottomSemi2.setRotationPoint(10F, 2F, 2F);
		BottomSemi2.setTextureSize(64, 32);
		BottomSemi2.mirror = true;
		setRotation(BottomSemi2, 0F, 0F, 0F);
		TLBar2 = new ModelRenderer(this, 0, 0);
		TLBar2.addBox(0F, 0F, 0F, 6, 1, 1);
		TLBar2.setRotationPoint(11F, -5F, 1F);
		TLBar2.setTextureSize(64, 32);
		TLBar2.mirror = true;
		setRotation(TLBar2, 0F, 0F, 0.7435722F);
		BLBar2 = new ModelRenderer(this, 0, 0);
		BLBar2.addBox(1F, 0F, 0F, 6, 1, 1);
		BLBar2.setRotationPoint(16F, 2F, 2F);
		BLBar2.setTextureSize(64, 32);
		BLBar2.mirror = true;
		setRotation(BLBar2, 0F, 0F, 2.379431F);
		BRBar2 = new ModelRenderer(this, 0, 0);
		BRBar2.addBox(0F, 0F, 0F, 6, 1, 1);
		BRBar2.setRotationPoint(5F, 2F, 1F);
		BRBar2.setTextureSize(64, 32);
		BRBar2.mirror = true;
		setRotation(BRBar2, 0F, 0F, 0.7435722F);
		TRBar2 = new ModelRenderer(this, 0, 0);
		TRBar2.addBox(0F, 0F, 0F, 6, 1, 1);
		TRBar2.setRotationPoint(9F, -4F, 2F);
		TRBar2.setTextureSize(64, 32);
		TRBar2.mirror = true;
		setRotation(TRBar2, 0F, 0F, 2.379431F);
		Top2 = new ModelRenderer(this, 0, 0);
		Top2.addBox(0F, 0F, 0F, 2, 2, 2);
		Top2.setRotationPoint(9F, -6F, 1F);
		Top2.setTextureSize(64, 32);
		Top2.mirror = true;
		setRotation(Top2, 0F, 0F, 0F);
		Right2 = new ModelRenderer(this, 0, 0);
		Right2.addBox(0F, 0F, 0F, 2, 2, 2);
		Right2.setRotationPoint(4F, 0F, 1F);
		Right2.setTextureSize(64, 32);
		Right2.mirror = true;
		setRotation(Right2, 0F, 0F, 0F);
		Left2 = new ModelRenderer(this, 0, 0);
		Left2.addBox(0F, 0F, 0F, 2, 2, 2);
		Left2.setRotationPoint(14F, 0F, 1F);
		Left2.setTextureSize(64, 32);
		Left2.mirror = true;
		setRotation(Left2, 0F, 0F, 0F);
		Bottom2 = new ModelRenderer(this, 0, 0);
		Bottom2.addBox(0F, 0F, 0F, 2, 2, 2);
		Bottom2.setRotationPoint(9F, 6F, 1F);
		Bottom2.setTextureSize(64, 32);
		Bottom2.mirror = true;
		setRotation(Bottom2, 0F, 0F, 0F);
		EyeRight2 = new ModelRenderer(this, 0, 10);
		EyeRight2.addBox(0F, 0F, 0F, 1, 1, 1);
		EyeRight2.setRotationPoint(7F, -2F, 0F);
		EyeRight2.setTextureSize(64, 32);
		EyeRight2.mirror = true;
		setRotation(EyeRight2, 0F, 0F, 0F);
		EyeLeft2 = new ModelRenderer(this, 0, 10);
		EyeLeft2.addBox(0F, 0F, 0F, 1, 1, 1);
		EyeLeft2.setRotationPoint(12F, -1F, 0F);
		EyeLeft2.setTextureSize(64, 32);
		EyeLeft2.mirror = true;
		setRotation(EyeLeft2, 0F, 0F, 0F);
		Bottom3 = new ModelRenderer(this, 0, 0);
		Bottom3.addBox(0F, 0F, 0F, 2, 2, 2);
		Bottom3.setRotationPoint(0F, 0F, -2F);
		Bottom3.setTextureSize(64, 32);
		Bottom3.mirror = true;
		setRotation(Bottom3, 0F, 0F, 0F);
		Middle3 = new ModelRenderer(this, 0, 0);
		Middle3.addBox(0F, 0F, 0F, 2, 2, 3);
		Middle3.setRotationPoint(0F, -6F, -2.5F);
		Middle3.setTextureSize(64, 32);
		Middle3.mirror = true;
		setRotation(Middle3, 0F, 0F, 0F);
		Top3 = new ModelRenderer(this, 0, 0);
		Top3.addBox(0F, 0F, 0F, 2, 2, 2);
		Top3.setRotationPoint(0F, -12F, -2F);
		Top3.setTextureSize(64, 32);
		Top3.mirror = true;
		setRotation(Top3, 0F, 0F, 0F);
		Right3 = new ModelRenderer(this, 0, 0);
		Right3.addBox(0F, 0F, 0F, 2, 2, 2);
		Right3.setRotationPoint(-5F, -6F, -2F);
		Right3.setTextureSize(64, 32);
		Right3.mirror = true;
		setRotation(Right3, 0F, 0F, 0F);
		Left3 = new ModelRenderer(this, 0, 0);
		Left3.addBox(0F, 0F, 0F, 2, 2, 2);
		Left3.setRotationPoint(5F, -6F, -2F);
		Left3.setTextureSize(64, 32);
		Left3.mirror = true;
		setRotation(Left3, 0F, 0F, 0F);
		BottomSemi3 = new ModelRenderer(this, 0, 0);
		BottomSemi3.addBox(0F, 0F, 0F, 1, 4, 1);
		BottomSemi3.setRotationPoint(1F, -4F, -1F);
		BottomSemi3.setTextureSize(64, 32);
		BottomSemi3.mirror = true;
		setRotation(BottomSemi3, 0F, 0F, 0F);
		TopSemi3 = new ModelRenderer(this, 0, 0);
		TopSemi3.addBox(0F, 0F, 0F, 1, 4, 1);
		TopSemi3.setRotationPoint(0F, -10F, -1F);
		TopSemi3.setTextureSize(64, 32);
		TopSemi3.mirror = true;
		setRotation(TopSemi3, 0F, 0F, 0F);
		LeftSemi3 = new ModelRenderer(this, 0, 0);
		LeftSemi3.addBox(0F, 0F, 0F, 3, 1, 1);
		LeftSemi3.setRotationPoint(2F, -6F, -1F);
		LeftSemi3.setTextureSize(64, 32);
		LeftSemi3.mirror = true;
		setRotation(LeftSemi3, 0F, 0F, 0F);
		RightSemi3 = new ModelRenderer(this, 0, 0);
		RightSemi3.addBox(0F, 0F, 0F, 3, 1, 1);
		RightSemi3.setRotationPoint(-3F, -5F, -2F);
		RightSemi3.setTextureSize(64, 32);
		RightSemi3.mirror = true;
		setRotation(RightSemi3, 0F, 0F, 0F);
		TRBar3 = new ModelRenderer(this, 0, 0);
		TRBar3.addBox(0F, 0F, 0F, 6, 1, 1);
		TRBar3.setRotationPoint(0F, -10F, -1F);
		TRBar3.setTextureSize(64, 32);
		TRBar3.mirror = true;
		setRotation(TRBar3, 0F, 0F, 2.379431F);
		TLBar3 = new ModelRenderer(this, 0, 0);
		TLBar3.addBox(0F, 0F, 0F, 6, 1, 1);
		TLBar3.setRotationPoint(2F, -11F, -2F);
		TLBar3.setTextureSize(64, 32);
		TLBar3.mirror = true;
		setRotation(TLBar3, 0F, 0F, 0.7435722F);
		BRBar3 = new ModelRenderer(this, 0, 0);
		BRBar3.addBox(0F, 0F, 0F, 6, 1, 1);
		BRBar3.setRotationPoint(-4F, -4F, -2F);
		BRBar3.setTextureSize(64, 32);
		BRBar3.mirror = true;
		setRotation(BRBar3, 0F, 0F, 0.7435722F);
		BLBar3 = new ModelRenderer(this, 0, 0);
		BLBar3.addBox(0F, 0F, 0F, 6, 1, 1);
		BLBar3.setRotationPoint(7F, -3F, -1F);
		BLBar3.setTextureSize(64, 32);
		BLBar3.mirror = true;
		setRotation(BLBar3, 0F, 0F, 2.379431F);
		EyeRight3 = new ModelRenderer(this, 0, 10);
		EyeRight3.addBox(0F, 0F, 0F, 1, 1, 1);
		EyeRight3.setRotationPoint(-2F, -4F, -3F);
		EyeRight3.setTextureSize(64, 32);
		EyeRight3.mirror = true;
		setRotation(EyeRight3, 0F, 0F, 0F);
		EyeLeft3 = new ModelRenderer(this, 0, 10);
		EyeLeft3.addBox(0F, 0F, 0F, 1, 1, 1);
		EyeLeft3.setRotationPoint(3F, -5F, -3F);
		EyeLeft3.setTextureSize(64, 32);
		EyeLeft3.mirror = true;
		setRotation(EyeLeft3, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Middle.render(f5);
		Top.render(f5);
		Bottom.render(f5);
		Left.render(f5);
		Right.render(f5);
		TopSemi.render(f5);
		BottomSemi.render(f5);
		LeftSemi.render(f5);
		RightSemi.render(f5);
		TLBar.render(f5);
		TRBar.render(f5);
		BRBar.render(f5);
		BLBar.render(f5);
		EyeRight.render(f5);
		EyeLeft.render(f5);
		Middle2.render(f5);
		LeftSemi2.render(f5);
		TopSemi2.render(f5);
		RightSemi2.render(f5);
		BottomSemi2.render(f5);
		TLBar2.render(f5);
		BLBar2.render(f5);
		BRBar2.render(f5);
		TRBar2.render(f5);
		Top2.render(f5);
		Right2.render(f5);
		Left2.render(f5);
		Bottom2.render(f5);
		EyeRight2.render(f5);
		EyeLeft2.render(f5);
		Bottom3.render(f5);
		Middle3.render(f5);
		Top3.render(f5);
		Right3.render(f5);
		Left3.render(f5);
		BottomSemi3.render(f5);
		TopSemi3.render(f5);
		LeftSemi3.render(f5);
		RightSemi3.render(f5);
		TRBar3.render(f5);
		TLBar3.render(f5);
		BRBar3.render(f5);
		BLBar3.render(f5);
		EyeRight3.render(f5);
		EyeLeft3.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
